modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="cheatmod"
version="1.0"
displayName="CheatMod"
description="A cheat mod for Minecraft 1.16.5 with Killaura, Fly, XRay, Speed, AntiKnockback, ESP, and ItemSwap"
[[dependencies.cheatmod]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="CLIENT"
[[dependencies.cheatmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="CLIENT"
